<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-E584GTO" ignored="3" name="Default test(failed)" tests="1" failures="0" timestamp="2023-02-02T15:35:26 IST" time="13.555" errors="0">
  <testcase name="@BeforeMethod beforeMethod" time="13.1" classname="testbase.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testbase.TestBase.beforeMethod(TestBase.java:42)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="-1.675332326373E9" classname="testbase.TestBase">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="loginTest" time="0.0" classname="tests.LoginTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="navigateToResetPassword" time="0.0" classname="tests.LoginTest">
    <ignored/>
  </testcase> <!-- navigateToResetPassword -->
  <testcase name="redirectToResetPasswordPageLinkPresent" time="0.0" classname="tests.LoginTest">
    <ignored/>
  </testcase> <!-- redirectToResetPasswordPageLinkPresent -->
  <testcase name="invalidLogin" time="0.0" classname="tests.LoginTest">
    <ignored/>
  </testcase> <!-- invalidLogin -->
</testsuite> <!-- Default test(failed) -->
